### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by mikoontz** [aurielfournier/CV#2]
Am I doing Github right? I don't know.

Nice CV! I was on the Big Island for a while as well. Were you in Hakalau?

Some typos I noticed, per your Twitter request:

1) There are 3 percent signs in your 3rd publication that I don't think should be there.
2) Work Experience -> Bird Bander -> Black Swamp Bird Observatory: "atleast" should be two words
3) Presentations: sometimes there is a comma after the final author and sometimes not
4) Presentations: sometimes there is a period after the title and sometimes not
5) Grants: I think the 'I' in 'Co-Pi' should be capitalized
6) Grants: Should there be a question mark at the end of the title of the 2011 Ecosystem Science Center award?
7) Grants: The oldest 3 grants have a different capitalization format for the titles than the newest grants
8) Leadership: For the U of Arkansas Wildlife Society position, multiple roles are listed on the same line but for the Grad Student Association position, multiple roles are on separate lines.

**Comment by aurielfournier** [comment]
I did a bit of work at Hakalau but was mostly working on the other side of Saddle Road in the Kipukas on a project with UH-Hilo and Michigan Tech.

Thanks for the comments, great catches! I've fixed them all.
